[32m2025-01-21 09:37:02 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c5bf4579-9f51-4882-9fd9-07b87b2bd0d5 - 352494 - LOGS_CAPTURED - Started capturing logs in process (pid: 352494).
[32m2025-01-21 09:37:02 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c5bf4579-9f51-4882-9fd9-07b87b2bd0d5 - 352494 - fetch_weather - STEP_START - Started execution of step "fetch_weather".
INFO:alembic.runtime.migration:Context impl SQLiteImpl.
INFO:alembic.runtime.migration:Will assume non-transactional DDL.
[32m2025-01-21 09:37:03 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c5bf4579-9f51-4882-9fd9-07b87b2bd0d5 - fetch_weather - Loading file from: /mnt/h/wsl_dagster/weather_project/tmp5sqw1x6z/storage/setup_database using PickledObjectFilesystemIOManager...
[32m2025-01-21 09:37:03 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c5bf4579-9f51-4882-9fd9-07b87b2bd0d5 - 352494 - fetch_weather - LOADED_INPUT - Loaded input "setup_database" using input manager "io_manager"
[32m2025-01-21 09:37:03 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c5bf4579-9f51-4882-9fd9-07b87b2bd0d5 - 352494 - fetch_weather - STEP_INPUT - Got input "setup_database" of type "Any". (Type check passed).
INFO:weather_project.assets:Fetching weather for Pune on 2025-01-15...
INFO:weather_project.assets:Weather data for Pune on 2025-01-15 fetched and stored successfully.
[32m2025-01-21 09:37:04 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - c5bf4579-9f51-4882-9fd9-07b87b2bd0d5 - 352494 - fetch_weather - STEP_FAILURE - Execution of step "fetch_weather" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "fetch_weather"::

TypeError: AssetResult.__new__() got an unexpected keyword argument 'value'

Stack Trace:
  File "/home/user_123/dagster_env/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 55, in op_execution_error_boundary
    yield
  File "/home/user_123/dagster_env/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 480, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/home/user_123/dagster_env/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 127, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/home/user_123/dagster_env/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 115, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/mnt/h/wsl_dagster/weather_project/weather_project/assets.py", line 46, in fetch_weather
    return MaterializeResult(
           ^^^^^^^^^^^^^^^^^^
[0m
